"""micro-niche suggestions: approval queue for audience-derived niches

A researched creator's audience problem clusters, proposed as seeds for the
niche drill engine and held for human approval before any LLM spend. See
corp/core/models/micro_niche.py for why this is its own table rather than
NicheCandidate rows.

Revision ID: 3793497b0a24
Revises: 873b4632a7c6
Create Date: 2026-09-23 14:49:21.842048

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3793497b0a24'
down_revision: str | Sequence[str] | None = '873b4632a7c6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('micro_niche_suggestions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('normalized_label', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='micronichestatus'), server_default='PENDING', nullable=False),
    sa.Column('problem_cluster_id', sa.String(length=36), nullable=True),
    sa.Column('creator_id', sa.String(length=36), nullable=True),
    sa.Column('creator_niche', sa.String(length=255), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('total_frequency', sa.Integer(), server_default='0', nullable=False),
    sa.Column('source_creator_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('approved_topic', sa.String(length=255), nullable=True),
    sa.Column('discovery_job_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['problem_cluster_id'], ['problem_clusters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_micro_niche_suggestions_normalized_label', 'micro_niche_suggestions', ['normalized_label'], unique=True)
    op.create_index('ix_micro_niche_suggestions_status', 'micro_niche_suggestions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_micro_niche_suggestions_status', table_name='micro_niche_suggestions')
    op.drop_index('ix_micro_niche_suggestions_normalized_label', table_name='micro_niche_suggestions')
    op.drop_table('micro_niche_suggestions')
    # ### end Alembic commands ###
    # drop_table leaves the enum type behind; without this a downgrade
    # followed by an upgrade fails with "type micronichestatus already exists".
    sa.Enum(name="micronichestatus").drop(op.get_bind(), checkfirst=True)
