"""integration: tier1-3 typed columns, competitors, run step log, FK repairs

Revision ID: 4aa6ae8d9e94
Revises: f6a7b8c9d0e1
Create Date: 2026-09-16 11:59:18.820967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4aa6ae8d9e94'
down_revision: Union[str, Sequence[str], None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('problem_cluster_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('competitor_type', sa.Enum('DIRECT', 'SUBSTITUTE', 'DIY_WORKAROUND', name='competitortype'), nullable=False),
    sa.Column('strength', sa.Enum('WEAK', 'MODERATE', 'STRONG', name='competitorstrength'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('gap_notes', sa.Text(), nullable=True),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['problem_cluster_id'], ['problem_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_competitors_cluster_id', 'competitors', ['problem_cluster_id'], unique=False)
    op.add_column('content_items', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('content_items', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('content_items', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('content_items', sa.Column('is_short', sa.Boolean(), nullable=True))
    op.add_column('creator_platform_accounts', sa.Column('total_view_count', sa.Integer(), nullable=True))
    op.add_column('creator_platform_accounts', sa.Column('video_count', sa.Integer(), nullable=True))
    op.add_column('creator_platform_accounts', sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('creator_platform_accounts', sa.Column('country', sa.String(length=10), nullable=True))
    op.add_column('creator_platform_accounts', sa.Column('description', sa.Text(), nullable=True))
    op.create_foreign_key(
        'fk_creator_scores_research_run_id', 'creator_scores', 'research_runs',
        ['research_run_id'], ['id'],
    )
    op.create_foreign_key(
        'fk_evidence_research_run_id', 'evidence', 'research_runs',
        ['research_run_id'], ['id'],
    )
    op.create_foreign_key(
        'fk_opportunity_scores_research_run_id', 'opportunity_scores', 'research_runs',
        ['research_run_id'], ['id'],
    )
    op.add_column('problem_observations', sa.Column('sentiment', sa.String(length=20), nullable=True))
    op.add_column('problem_observations', sa.Column('urgency', sa.String(length=20), nullable=True))
    op.add_column('research_runs', sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_runs', 'steps')
    op.drop_column('problem_observations', 'urgency')
    op.drop_column('problem_observations', 'sentiment')
    op.drop_constraint('fk_opportunity_scores_research_run_id', 'opportunity_scores', type_='foreignkey')
    op.drop_constraint('fk_evidence_research_run_id', 'evidence', type_='foreignkey')
    op.drop_constraint('fk_creator_scores_research_run_id', 'creator_scores', type_='foreignkey')
    op.drop_column('creator_platform_accounts', 'description')
    op.drop_column('creator_platform_accounts', 'country')
    op.drop_column('creator_platform_accounts', 'joined_at')
    op.drop_column('creator_platform_accounts', 'video_count')
    op.drop_column('creator_platform_accounts', 'total_view_count')
    op.drop_column('content_items', 'is_short')
    op.drop_column('content_items', 'language')
    op.drop_column('content_items', 'tags')
    op.drop_column('content_items', 'duration')
    op.drop_index('ix_competitors_cluster_id', table_name='competitors')
    op.drop_table('competitors')
    sa.Enum(name='competitortype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='competitorstrength').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
