"""initial schema - all 13 tables with indexes and pgvector

Revision ID: 5c4a27a2ac92
Revises: 
Create Date: 2026-09-12 11:54:34.068389

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c4a27a2ac92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector must exist before any VECTOR column is created below. The image
    # (pgvector/pgvector:pg16) ships the extension but does not enable it per
    # database, so a fresh DB fails with 'type "vector" does not exist' without
    # this. Requires a role allowed to CREATE EXTENSION (the compose superuser is).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creators',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('niche', sa.String(length=255), nullable=True),
    sa.Column('discovery_source', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DISCOVERED', 'COLLECTING', 'COLLECTED', 'EXTRACTING', 'EXTRACTED', 'CLUSTERING', 'CLUSTERED', 'SCORING', 'SCORED', 'RESEARCH_COMPLETE', 'HUMAN_REVIEW', 'APPROVED', 'REJECTED', 'WATCHING', 'DOSSIER_GENERATED', 'OUTREACH_READY', 'IN_OUTREACH', 'PARTNERSHIP', name='creatorstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_creators_niche', 'creators', ['niche'], unique=False)
    op.create_index('ix_creators_status', 'creators', ['status'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_platform', sa.String(length=50), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('author_handle', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('access_method', sa.Enum('OFFICIAL', 'VENDOR_SCRAPE', 'OPEN', name='accessmethod'), nullable=False),
    sa.Column('compliance_status', sa.Enum('COMPLIANT', 'TOS_RISK', 'PII_PRESENT', 'VERIFY', name='compliancestatus'), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('research_run_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_platform', 'evidence', ['source_platform'], unique=False)
    op.create_index('ix_evidence_research_run', 'evidence', ['research_run_id'], unique=False)
    op.create_index('ix_evidence_source', 'evidence', ['source_type', 'source_id'], unique=False)
    op.create_table('problem_clusters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('recency_score', sa.Float(), nullable=False),
    sa.Column('evidence_strength', sa.Float(), nullable=False),
    sa.Column('creator_count', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commercial_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('problem_cluster_id', sa.String(length=36), nullable=False),
    sa.Column('signal_level', sa.Enum('WEAK', 'MODERATE', 'STRONG', 'VALIDATION', name='signallevel'), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('classification_model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['problem_cluster_id'], ['problem_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Enum('VIDEO', 'POST', 'STORY', 'REEL', 'SHORT', 'ARTICLE', 'THREAD', name='contenttype'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_content_items_creator_id', 'content_items', ['creator_id'], unique=False)
    op.create_index('ix_content_items_platform_ext', 'content_items', ['platform', 'external_id'], unique=True)
    op.create_table('creator_platform_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cpa_creator_id', 'creator_platform_accounts', ['creator_id'], unique=False)
    op.create_index('ix_cpa_platform_handle', 'creator_platform_accounts', ['platform', 'handle'], unique=True)
    op.create_table('creator_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('component_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aggregate_score', sa.Float(), nullable=False),
    sa.Column('computed_hash', sa.String(length=64), nullable=False),
    sa.Column('confidence_band', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'INSUFFICIENT', name='confidenceband'), nullable=False),
    sa.Column('rule_version', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('research_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_creator_scores_creator_id', 'creator_scores', ['creator_id'], unique=False)
    op.create_table('opportunity_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('problem_cluster_id', sa.String(length=36), nullable=False),
    sa.Column('component_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aggregate_score', sa.Float(), nullable=False),
    sa.Column('computed_hash', sa.String(length=64), nullable=False),
    sa.Column('confidence_band', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'INSUFFICIENT', name='confidenceband'), nullable=False),
    sa.Column('rule_version', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('research_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['problem_cluster_id'], ['problem_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_opp_scores_cluster_id', 'opportunity_scores', ['problem_cluster_id'], unique=False)
    op.create_index('ix_opp_scores_creator_id', 'opportunity_scores', ['creator_id'], unique=False)
    op.create_table('problem_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_inferred', sa.Boolean(), nullable=False),
    sa.Column('extraction_prompt_version', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_observations_category', 'problem_observations', ['category'], unique=False)
    op.create_index('ix_observations_evidence_id', 'problem_observations', ['evidence_id'], unique=False)
    op.create_table('research_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runs_creator_id', 'research_runs', ['creator_id'], unique=False)
    op.create_table('audience_interactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content_item_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author_handle', sa.String(length=255), nullable=True),
    sa.Column('interaction_type', sa.Enum('COMMENT', 'REPLY', 'QUESTION', 'REVIEW', name='interactiontype'), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interactions_content_item_id', 'audience_interactions', ['content_item_id'], unique=False)
    op.create_index('ix_interactions_external_id', 'audience_interactions', ['external_id'], unique=False)
    op.create_table('human_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_score_id', sa.String(length=36), nullable=True),
    sa.Column('decision', sa.Enum('APPROVE', 'REJECT', 'WATCH', name='decisiontype'), nullable=False),
    sa.Column('gate', sa.Enum('GATE_A', 'GATE_B', 'GATE_C', 'GATE_D', 'GATE_E', name='gate'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['opportunity_score_id'], ['opportunity_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decisions_creator_id', 'human_decisions', ['creator_id'], unique=False)
    op.create_index('ix_decisions_gate', 'human_decisions', ['gate'], unique=False)
    op.create_table('problem_cluster_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=False),
    sa.Column('observation_id', sa.String(length=36), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['problem_clusters.id'], ),
    sa.ForeignKeyConstraint(['observation_id'], ['problem_observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pcm_cluster_id', 'problem_cluster_members', ['cluster_id'], unique=False)
    op.create_index('ix_pcm_observation_id', 'problem_cluster_members', ['observation_id'], unique=False)
    op.create_index('ix_pcm_unique', 'problem_cluster_members', ['cluster_id', 'observation_id'], unique=True)
    # ### end Alembic commands ###

    # Evidence append-only: block UPDATE and DELETE via trigger
    op.execute("""
        CREATE OR REPLACE FUNCTION prevent_evidence_mutation()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION 'Evidence table is append-only. UPDATE and DELETE are prohibited.';
            RETURN NULL;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER evidence_no_update
        BEFORE UPDATE ON evidence
        FOR EACH ROW EXECUTE FUNCTION prevent_evidence_mutation();
    """)
    op.execute("""
        CREATE TRIGGER evidence_no_delete
        BEFORE DELETE ON evidence
        FOR EACH ROW EXECUTE FUNCTION prevent_evidence_mutation();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS evidence_no_delete ON evidence;")
    op.execute("DROP TRIGGER IF EXISTS evidence_no_update ON evidence;")
    op.execute("DROP FUNCTION IF EXISTS prevent_evidence_mutation();")
    op.drop_index('ix_pcm_unique', table_name='problem_cluster_members')
    op.drop_index('ix_pcm_observation_id', table_name='problem_cluster_members')
    op.drop_index('ix_pcm_cluster_id', table_name='problem_cluster_members')
    op.drop_table('problem_cluster_members')
    op.drop_index('ix_decisions_gate', table_name='human_decisions')
    op.drop_index('ix_decisions_creator_id', table_name='human_decisions')
    op.drop_table('human_decisions')
    op.drop_index('ix_interactions_external_id', table_name='audience_interactions')
    op.drop_index('ix_interactions_content_item_id', table_name='audience_interactions')
    op.drop_table('audience_interactions')
    op.drop_index('ix_runs_creator_id', table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_index('ix_observations_evidence_id', table_name='problem_observations')
    op.drop_index('ix_observations_category', table_name='problem_observations')
    op.drop_table('problem_observations')
    op.drop_index('ix_opp_scores_creator_id', table_name='opportunity_scores')
    op.drop_index('ix_opp_scores_cluster_id', table_name='opportunity_scores')
    op.drop_table('opportunity_scores')
    op.drop_index('ix_creator_scores_creator_id', table_name='creator_scores')
    op.drop_table('creator_scores')
    op.drop_index('ix_cpa_platform_handle', table_name='creator_platform_accounts')
    op.drop_index('ix_cpa_creator_id', table_name='creator_platform_accounts')
    op.drop_table('creator_platform_accounts')
    op.drop_index('ix_content_items_platform_ext', table_name='content_items')
    op.drop_index('ix_content_items_creator_id', table_name='content_items')
    op.drop_table('content_items')
    op.drop_table('commercial_signals')
    op.drop_table('problem_clusters')
    op.drop_index('ix_evidence_source', table_name='evidence')
    op.drop_index('ix_evidence_research_run', table_name='evidence')
    op.drop_index('ix_evidence_platform', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_creators_status', table_name='creators')
    op.drop_index('ix_creators_niche', table_name='creators')
    op.drop_table('creators')
    # ### end Alembic commands ###

    for enum_name in [
        'creatorstatus', 'accessmethod', 'compliancestatus', 'contenttype',
        'interactiontype', 'signallevel', 'confidenceband', 'decisiontype', 'gate',
    ]:
        op.execute(f"DROP TYPE IF EXISTS {enum_name};")
