"""extraction stamps on audience_interactions

Revision ID: 6c88964d1240
Revises: f6a7b8c9d0e1
Create Date: 2026-09-16 14:03:58.991575

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6c88964d1240'
down_revision: str | Sequence[str] | None = 'f6a7b8c9d0e1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audience_interactions', sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('audience_interactions', sa.Column('extracted_prompt_version', sa.String(length=50), nullable=True))
    op.add_column('audience_interactions', sa.Column('extracted_model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audience_interactions', 'extracted_model')
    op.drop_column('audience_interactions', 'extracted_prompt_version')
    op.drop_column('audience_interactions', 'extracted_at')
    # ### end Alembic commands ###
