"""r14_creator_archive

Revision ID: 873b4632a7c6
Revises: f6a1e362c878
Create Date: 2026-09-22 20:44:56.056957

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '873b4632a7c6'
down_revision: str | Sequence[str] | None = 'f6a1e362c878'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creators', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_creators_archived_at', 'creators', ['archived_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_creators_archived_at', table_name='creators')
    op.drop_column('creators', 'archived_at')
    # ### end Alembic commands ###
