"""add unique slug to campaigns for enforceable autonomous-campaign identity

Revision ID: 8fb35dc16e35
Revises: 3793497b0a24
Create Date: 2026-09-24 00:08:11.494715

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8fb35dc16e35'
down_revision: str | Sequence[str] | None = '3793497b0a24'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('campaigns', sa.Column('slug', sa.String(length=100), nullable=True))

    # Backfill: get_or_create_autonomous_campaign() has always matched by
    # name (case-insensitive), so a deployment that already ran discovery
    # has an "Autonomous discovery" campaign with no slug yet. Give it one
    # so startup finds it instead of creating a second copy. The race this
    # migration exists to close (two near-simultaneous passes each
    # inserting their own campaign) could already have produced duplicates
    # of that name — pick only the oldest one; any others are left as
    # ordinary campaigns rather than failing this migration on the new
    # unique index.
    op.execute(
        """
        UPDATE campaigns
        SET slug = 'autonomous-discovery'
        WHERE id = (
            SELECT id FROM campaigns
            WHERE lower(name) = 'autonomous discovery'
            ORDER BY created_at ASC
            LIMIT 1
        )
        """
    )

    op.create_index('ix_campaigns_slug', 'campaigns', ['slug'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_campaigns_slug', table_name='campaigns')
    op.drop_column('campaigns', 'slug')
    # ### end Alembic commands ###
